local colors = require("prism.themer"):getColors()
local utils = require("prism.utils")

return {
  CmpItemKindClass = { bg = colors.color4, fg = colors.black },
  CmpItemKindEnum = { bg = colors.color5, fg = colors.black },
  CmpItemKindEnumMember = { bg = colors.color5, fg = colors.black },
  CmpItemKindSnippet = { bg = colors.color10, fg = colors.black },
  CmpItemKindField = { bg = colors.color10, fg = colors.black },
  CmpItemKindText = { bg = colors.color12, fg = colors.black },
  CmpItemKindConstant = { bg = colors.color11, fg = colors.black },
  CmpItemKindConstructor = { bg = colors.color10, fg = colors.black },
  CmpItemKindFunction = { bg = colors.color12, fg = colors.black },
  CmpItemKindKeyword = { bg = colors.color5, fg = colors.black },
  CmpItemKindOperator = { bg = colors.color12, fg = colors.black },
  CmpItemKindProperty = { bg = colors.color5, fg = colors.black },
  CmpItemKindStruct = { bg = colors.color12, fg = colors.black },
  CmpItemKindTypeParameter = { bg = colors.color2, fg = colors.black },
  CmpItemKindUnit = { bg = colors.color12, fg = colors.black },
  CmpItemKindValue = { bg = colors.color10, fg = colors.black },
  CmpItemKindVariable = { bg = colors.color1, fg = colors.black },
  CmpItemKindCodeium = { bg = colors.color2, fg = colors.black },
  CmpItemAbbr = { fg = colors.foreground },
  CmpItemAbbrDeprecated = { fg = colors.color2 },
  CmpItemAbbrMatch = { fg = colors.color7 },
  CmpItemAbbrMatchFuzzy = { fg = colors.color7 },
  CmpItemKind = { fg = colors.foreground },
  CmpItemMenu = { fg = colors.foreground },
  CmpDoc = { bg = colors.cursorline },
  Pmenu = { fg = colors.foreground, bg = colors.darker },
  PmenuSel = { bg = utils.darken(colors.color4, colors.darker, 0.4) },
  PmenuSbar = { bg = colors.darker },
  PmenuThumb = { bg = colors.color2 },
}
